/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.main;

import br.com.ecommerce.classes.CarregaDadosModeloUsuario;
import br.com.ecommerce.classes.Produto;
import br.com.ecommerce.classes.Usuario;
import br.com.ecommerce.dao.FiltroDAO;
import br.com.ecommerce.dao.InnerJoinProdutoUsuarioDAO;
import br.com.ecommerce.dao.ProdutoDAO;
import br.com.ecommerce.enumeracoes.EstadoProduto;
import br.com.ecommerce.tables.ModeloMainUsuario;
import br.com.ecommerce.view.att.endereco.TelaAtualizarEndereco;
import br.com.ecommerce.view.att.usuarios.TelaAtualizarDadosAcesso;
import br.com.ecommerce.view.att.usuarios.TelaAtualizarDadosPessoais;
import br.com.ecommerce.view.cadastro.enderecos.TelaCadastroEndereco;
import br.com.ecommerce.view.carrinhocompras.TelaLimparCarrinho;
import br.com.ecommerce.view.carrinhocompras.TelaVisualizarCarrinhoCompras;
import br.com.ecommerce.view.compra.TelaFinalizarCompraCarrinho;
import br.com.ecommerce.view.delete.usuario.TelaDeletarUsuario;
import br.com.ecommerce.view.login.JTextFieldHint;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public final class TelaPrincipalUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalUsuario
     */
    
    private Usuario usuario;
    private ModeloMainUsuario modelo;
    
    public TelaPrincipalUsuario() {
        initialize();
    }

    public TelaPrincipalUsuario(Usuario u) {
        this.usuario = u;
        initialize();
    }
    
    public void initialize() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        modelo = new ModeloMainUsuario();
        tabela_main_usuario.setModel(modelo);
//        suporteCarregaDados();
        new Thread(new CarregaDadosModeloUsuario(modelo)).start();
        suporteCarregaItensCombo();
        comboListener();
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
//    private void suporteCarregaDados() {
//        modelo.clearMap();
//        try {
//            List<Produto> lista;
//            if((lista = new ProdutoDAO().listaProdutosUsuario(true, -1)) != null)
//                for(Produto aux : lista)
//                    if(aux.getSituacao() == EstadoProduto.ESTOQUE)
//                        modelo.addProduto(aux, false);
//        } catch (SQLException ex) {
//            ex.printStackTrace();
//            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
//        }
//    }
    
    private void suporteCarregaItensCombo (){
        List<String> categorias = null;
        try {
            categorias = new FiltroDAO().getCategorias();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        for(String aux : categorias) combobox_mainuser.addItem(aux);
    }
    
    public void comboListener(){
        combobox_mainuser.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getStateChange() == ItemEvent.SELECTED){
                    String categoria = (String) combobox_mainuser.getSelectedItem();
                    if(categoria.equals("Todas")) new Thread(new CarregaDadosModeloUsuario(modelo)).start();
                    else {
                        List<Produto> list = null;
                        try {
                            list = new FiltroDAO().separaPorCategoria(categoria);
                        } catch (SQLException ex) {
                            ex.printStackTrace();
                            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
                        }
                        if(list == null) {
                            JOptionPane.showMessageDialog(null, "Nenhum produto disponível nesta categoria");
                            new Thread(new CarregaDadosModeloUsuario(modelo)).start();
                            return;
                        }
                        modelo.clearMap();
                        for(Produto aux: list) modelo.addProduto(aux, false);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_main_usuario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        in_mainuser_minimo = new JTextFieldHint(new JTextField(), "", "Mínimo de:");
        in_mainuser_maximo = new JTextFieldHint(new JTextField(), "", "Máximo de:");
        btn_mainuser_filtros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        in_mainuser_nomebusca = new JTextFieldHint(new JTextField(), "", "Nome do produto");
        btn_mainuser_buscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        combobox_mainuser = new javax.swing.JComboBox<>();
        btn_mainuser_comprar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        tabela_main_usuario.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tabela_main_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela_main_usuario.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tabela_main_usuario);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Preço mínimo");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Preço máximo");

        in_mainuser_minimo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_mainuser_maximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_mainuser_filtros.setBackground(new java.awt.Color(255, 255, 255));
        btn_mainuser_filtros.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_mainuser_filtros.setText("Aplicar filtros");
        btn_mainuser_filtros.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_mainuser_filtros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mainuser_filtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mainuser_filtrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mainuser_filtrosMouseExited(evt);
            }
        });
        btn_mainuser_filtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainuser_filtrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(in_mainuser_maximo, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(in_mainuser_minimo)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_mainuser_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(in_mainuser_minimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_mainuser_maximo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_mainuser_filtros, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtros");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Busca");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Busca pelo nome do produto");

        in_mainuser_nomebusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_mainuser_buscar.setBackground(new java.awt.Color(255, 255, 255));
        btn_mainuser_buscar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_mainuser_buscar.setText("Buscar");
        btn_mainuser_buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_mainuser_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mainuser_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mainuser_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mainuser_buscarMouseExited(evt);
            }
        });
        btn_mainuser_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainuser_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(in_mainuser_nomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btn_mainuser_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_mainuser_nomebusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_mainuser_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lista de produtos");

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria");

        combobox_mainuser.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        combobox_mainuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas" }));

        btn_mainuser_comprar.setBackground(new java.awt.Color(160, 82, 45));
        btn_mainuser_comprar.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        btn_mainuser_comprar.setForeground(new java.awt.Color(255, 255, 255));
        btn_mainuser_comprar.setText("Adicionar ao carrinho");
        btn_mainuser_comprar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_mainuser_comprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mainuser_comprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_mainuser_comprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_mainuser_comprarMouseExited(evt);
            }
        });
        btn_mainuser_comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mainuser_comprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(255, 255, 255))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(combobox_mainuser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(83, 83, 83)))
                .addComponent(btn_mainuser_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combobox_mainuser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_mainuser_comprar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("Usuario");

        jMenuItem1.setText("Novo endereço");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Atualizar endereço");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Atualizar dados pessoais");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Atualizar dados de acesso");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        jMenuItem9.setText("Deletar conta");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Carrinho");

        jMenuItem5.setText("Visualizar carrinho");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Limpar carrinho");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Compra");

        jMenuItem7.setText("Finalizar compra");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCadastroEndereco tela = new TelaCadastroEndereco(usuario.getId());
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaAtualizarEndereco tela = new TelaAtualizarEndereco(usuario.getId());
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaAtualizarDadosPessoais tela = new TelaAtualizarDadosPessoais(usuario);
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaAtualizarDadosAcesso tela = new TelaAtualizarDadosAcesso(usuario);
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMenuItem4ActionPerformed
	
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaVisualizarCarrinhoCompras tela = new TelaVisualizarCarrinhoCompras(usuario.getId(), modelo);
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        TelaLimparCarrinho tela = new TelaLimparCarrinho(usuario.getId(), modelo);
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }                                           

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        TelaDeletarUsuario tela = new TelaDeletarUsuario(usuario.getId());
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btn_mainuser_filtrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainuser_filtrosMouseEntered
        btn_mainuser_filtros.setBackground(Color.BLUE);
        btn_mainuser_filtros.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_mainuser_filtrosMouseEntered

    private void btn_mainuser_filtrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainuser_filtrosMouseExited
        btn_mainuser_filtros.setBackground(Color.WHITE);
        btn_mainuser_filtros.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_mainuser_filtrosMouseExited

    private void btn_mainuser_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainuser_buscarMouseEntered
        btn_mainuser_buscar.setBackground(Color.BLUE);
        btn_mainuser_buscar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_mainuser_buscarMouseEntered

    private void btn_mainuser_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainuser_buscarMouseExited
        btn_mainuser_buscar.setBackground(Color.WHITE);
        btn_mainuser_buscar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_mainuser_buscarMouseExited

    private void btn_mainuser_comprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainuser_comprarMouseEntered
        btn_mainuser_comprar.setBackground(new Color(210,105,30));
    }//GEN-LAST:event_btn_mainuser_comprarMouseEntered

    private void btn_mainuser_comprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mainuser_comprarMouseExited
        btn_mainuser_comprar.setBackground(new Color(160,82,45));
    }//GEN-LAST:event_btn_mainuser_comprarMouseExited
    
    public void cleanFiltrosPreco() {
        in_mainuser_maximo.setText("");
        in_mainuser_minimo.setText("");
    }
    
    private void btn_mainuser_filtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainuser_filtrosActionPerformed
        
        String sMinimo = in_mainuser_minimo.getText();
        String sMaximo = in_mainuser_maximo.getText();
        if(sMinimo.equals("") && sMaximo.equals("")){
            new Thread(new CarregaDadosModeloUsuario(modelo)).start();
            in_mainuser_nomebusca.setText("");
            combobox_mainuser.setSelectedItem("Todas");
            return;
        }
        
        Double minimo;
        if(sMinimo.equals("")) minimo = 0d;
        else try {
            minimo = Double.parseDouble(sMinimo);
        } catch (NumberFormatException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Valor mínimo inválido");
            return;
        }
        
        Double maximo;
        if(sMaximo.equals("")) maximo = null;
        else try{
            maximo = Double.parseDouble(sMaximo);
        } catch (NumberFormatException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Valor máximo inválido");
            return;
        } 
        
        List<Produto> list = null;
        try {
            list = new FiltroDAO().precoEntreValores(minimo, maximo);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(list == null) {
            JOptionPane.showMessageDialog(null, "Nenhum produto corresponde a busca");
            new Thread(new CarregaDadosModeloUsuario(modelo)).start();
            cleanFiltrosPreco();
            in_mainuser_nomebusca.setText("");
            combobox_mainuser.setSelectedItem("Todas");
            return;
        }
        
        modelo.clearMap();
        for(Produto p: list) modelo.addProduto(p, false);
        in_mainuser_nomebusca.setText("");
        combobox_mainuser.setSelectedItem("Todas");
        
    }//GEN-LAST:event_btn_mainuser_filtrosActionPerformed
    
    private void btn_mainuser_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainuser_buscarActionPerformed
        String nomeBusca = in_mainuser_nomebusca.getText();
        if(nomeBusca.equals("")){
            new Thread(new CarregaDadosModeloUsuario(modelo)).start();
            cleanFiltrosPreco();
            return;
        }

        List<Produto> list = null;
        try {
            list = new FiltroDAO().buscarNome(nomeBusca);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(list == null){
            JOptionPane.showMessageDialog(null, "Nenhum produto corresponde a busca");
            new Thread(new CarregaDadosModeloUsuario(modelo)).start();
            in_mainuser_nomebusca.setText("");
            return;
        }
        
        modelo.clearMap();
        for(Produto p: list) modelo.addProduto(p, false);
        cleanFiltrosPreco();

    }//GEN-LAST:event_btn_mainuser_buscarActionPerformed

    private void btn_mainuser_comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mainuser_comprarActionPerformed
        
        int index = tabela_main_usuario.getSelectedRow();
        if(index == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um produto para poder adicioná-lo ao carrinho");
            return;
        }
        
        Produto p = modelo.getProdutoIndex(index);
        if(modelo.quantidadeProduto(p) == 1){
            p.setId_foreign(usuario.getId());
            p.setSituacao(EstadoProduto.INDISPONIVEL);
            try {
                new ProdutoDAO().atualizarProduto(p);
                modelo.setValueAt(modelo.quantidadeProduto(p)-1, index, 3);
                JOptionPane.showMessageDialog(null, "Produto adicionado ao carrinho com sucesso!");
            } catch (SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
            }
        } else {
            String input = JOptionPane.showInputDialog("Informe a quantidade");
            if(input == null) return;
            
            Integer quantidade = null;
            Integer qntOld = modelo.quantidadeProduto(p);
            try {
                quantidade = Integer.parseInt(input);
            } catch (NumberFormatException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Por favor, informe um número válido para a quantidade");
                return;
            }
            
            if(quantidade > qntOld){
                JOptionPane.showMessageDialog(null, "Desculpe, há apenas "+qntOld+" unidades deste produto no estoque");
                return;
            } else if (quantidade < 0){
                JOptionPane.showMessageDialog(null, "Desculpe, valores negativos são inválidos");
                return;
            }
            
            List<Produto> disponiveis = null;
            try {
                disponiveis = new ProdutoDAO().listaProdutosDisponiveis(p.getNome());
                for(int i=0 ; i<quantidade ; i++){
                    disponiveis.get(i).setSituacao(EstadoProduto.INDISPONIVEL);
                    disponiveis.get(i).setId_foreign(usuario.getId());
                    new ProdutoDAO().atualizarProduto(disponiveis.get(i));
                    modelo.setValueAt(qntOld-quantidade, index, 3);
                }
                JOptionPane.showMessageDialog(null, "Unidades adicionadas ao carrinho com sucesso!");
            } catch (SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
            }
        }
        tabela_main_usuario.clearSelection();

    }//GEN-LAST:event_btn_mainuser_comprarActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try{
            if(new InnerJoinProdutoUsuarioDAO().listaProdutosUsuario(usuario.getId()) == null){
                JOptionPane.showMessageDialog(null, "O seu carrinho de compras está vazio");
                return;
            }
        } catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        TelaFinalizarCompraCarrinho tela = new TelaFinalizarCompraCarrinho(usuario.getId(), jDesktopPane1);
        jDesktopPane1.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mainuser_buscar;
    private javax.swing.JButton btn_mainuser_comprar;
    private javax.swing.JButton btn_mainuser_filtros;
    private javax.swing.JComboBox<String> combobox_mainuser;
    private javax.swing.JTextField in_mainuser_maximo;
    private javax.swing.JTextField in_mainuser_minimo;
    private javax.swing.JTextField in_mainuser_nomebusca;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable tabela_main_usuario;
    // End of variables declaration//GEN-END:variables
}
