/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.cadastro.enderecos;

import br.com.ecommerce.classes.Endereco;
import br.com.ecommerce.classes.PosicaoInternalFrame;
import br.com.ecommerce.dao.EnderecoDAO;
import br.com.ecommerce.view.login.JTextFieldHint;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class TelaCadastroEndereco extends PosicaoInternalFrame {

    /**
     * Creates new form TelaCadastroEndereco
     */
    private Integer id;
    
    public TelaCadastroEndereco(Integer id_usuario) {
        initComponents();
        this.id = id_usuario;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        in_cadend_rua = new JTextFieldHint(new JTextField(), "", "Rua");
        in_cadend_cidade = new JTextFieldHint(new JTextField(), "", "Cidade");
        in_cadend_cep = new javax.swing.JFormattedTextField();
        in_cadend_numero = new JTextFieldHint(new JTextField(), "", "Número/apto e bloco");
        in_cadend_complemento = new JTextFieldHint(new JTextField(), "", "Complemento, referências");
        btn_cadend_enviar = new javax.swing.JButton();
        btn_cadend_cancelar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        jPanel2.setBackground(new java.awt.Color(18, 7, 80));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de novo endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cidade");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rua");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CEP");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número/apto");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Complemento");

        in_cadend_rua.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_cadend_rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_cadend_cidade.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_cadend_cidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_cadend_cep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            in_cadend_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        in_cadend_cep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        in_cadend_numero.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_cadend_numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_cadend_complemento.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_cadend_complemento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(in_cadend_rua)
                    .addComponent(in_cadend_cidade)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(in_cadend_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(in_cadend_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(in_cadend_complemento))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_cadend_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(in_cadend_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(in_cadend_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(in_cadend_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(in_cadend_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        btn_cadend_enviar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadend_enviar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_cadend_enviar.setText("Enviar");
        btn_cadend_enviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_cadend_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadend_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cadend_enviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cadend_enviarMouseExited(evt);
            }
        });
        btn_cadend_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadend_enviarActionPerformed(evt);
            }
        });

        btn_cadend_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cadend_cancelar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_cadend_cancelar.setText("Cancelar");
        btn_cadend_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_cadend_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadend_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cadend_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cadend_cancelarMouseExited(evt);
            }
        });
        btn_cadend_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadend_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btn_cadend_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btn_cadend_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cadend_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadend_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadend_enviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadend_enviarMouseEntered
        btn_cadend_enviar.setBackground(Color.GREEN);
        btn_cadend_enviar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_cadend_enviarMouseEntered

    private void btn_cadend_enviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadend_enviarMouseExited
        btn_cadend_enviar.setBackground(Color.WHITE);
        btn_cadend_enviar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_cadend_enviarMouseExited

    private void btn_cadend_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadend_cancelarMouseEntered
        btn_cadend_cancelar.setBackground(Color.RED);
        btn_cadend_cancelar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_cadend_cancelarMouseEntered

    private void btn_cadend_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cadend_cancelarMouseExited
        btn_cadend_cancelar.setBackground(Color.WHITE);
        btn_cadend_cancelar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_cadend_cancelarMouseExited

    private void btn_cadend_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadend_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_cadend_cancelarActionPerformed

    private void btn_cadend_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadend_enviarActionPerformed
        
        String rua = in_cadend_rua.getText();
        if(rua.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o nome da rua");
            return;
        }
        
        String cidade = in_cadend_cidade.getText();
        if(cidade.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o nome da cidade");
            return;
        }
        
        String cep = in_cadend_cep.getText();
        if(cep.equals("") || cep.equals("     .   ") || cep == null) {
            JOptionPane.showMessageDialog(null, "Por favor, informe um CEP");
            return;
        }
        
        String numero = in_cadend_numero.getText();
        if(numero.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o número/apartamento do endereço");
            return;
        }
        
        String complemento = in_cadend_complemento.getText();
        
        Endereco e = new Endereco(rua, cidade, cep, numero);
        e.setComplemento(complemento);
        e.setId_foreign(id);
        
        try {
            EnderecoDAO eD = new EnderecoDAO();
            eD.addEndereco(e);
            JOptionPane.showMessageDialog(null, "Endereço cadastrado com sucesso!");
            dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        
    }//GEN-LAST:event_btn_cadend_enviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadend_cancelar;
    private javax.swing.JButton btn_cadend_enviar;
    private javax.swing.JFormattedTextField in_cadend_cep;
    private javax.swing.JTextField in_cadend_cidade;
    private javax.swing.JTextField in_cadend_complemento;
    private javax.swing.JTextField in_cadend_numero;
    private javax.swing.JTextField in_cadend_rua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
