/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.att.usuarios;

import br.com.ecommerce.classes.PosicaoInternalFrame;
import br.com.ecommerce.classes.Usuario;
import br.com.ecommerce.dao.UsuarioDAO;
import br.com.ecommerce.enumeracoes.TipoUsuario;
import br.com.ecommerce.expressao_regular.ValidaEmail;
import br.com.ecommerce.view.login.JPassWordFieldHint;
import br.com.ecommerce.view.login.JTextFieldHint;
import br.com.ecommerce.view.main.TelaPrincipalGerente;
import br.com.ecommerce.view.main.TelaPrincipalUsuario;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class TelaAtualizarDadosAcesso extends PosicaoInternalFrame {

    /**
     * Creates new form TelaAtualizarDadosAcesso
     */
    
    private Usuario user;
    
    public TelaAtualizarDadosAcesso(Usuario u) {
        initComponents();
        setResizable(false);
        this.user = u;
        in_attacesso_email.setText(user.getEmail());
    }
    
    public Usuario getUsuario() {
        return user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_attacesso_enviar = new javax.swing.JButton();
        in_attacesso_email = new JTextFieldHint(new JTextField(), "", "E-mail do usuário");
        in_attacesso_oldpass = new JPassWordFieldHint(new JPasswordField(), "" , "Senha antiga para validação");
        in_attacesso_newpass1 = new JPassWordFieldHint(new JPasswordField(), "" , "Senha nova. Máximo de 20 caracteres");
        in_attacesso_newpass2 = new JPassWordFieldHint(new JPasswordField(), "" , "Confirme a nova senha");

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-mail");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha antiga");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha nova");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirmar senha nova");

        btn_attacesso_enviar.setBackground(new java.awt.Color(255, 255, 255));
        btn_attacesso_enviar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_attacesso_enviar.setText("Enviar");
        btn_attacesso_enviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_attacesso_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attacesso_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_attacesso_enviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_attacesso_enviarMouseExited(evt);
            }
        });
        btn_attacesso_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attacesso_enviarActionPerformed(evt);
            }
        });

        in_attacesso_email.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attacesso_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_attacesso_oldpass.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attacesso_oldpass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_attacesso_newpass1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attacesso_newpass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_attacesso_newpass2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attacesso_newpass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(in_attacesso_email))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(in_attacesso_newpass2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(in_attacesso_oldpass, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(in_attacesso_newpass1))))
                        .addGap(87, 87, 87)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addComponent(btn_attacesso_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(in_attacesso_email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(in_attacesso_oldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_attacesso_newpass1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_attacesso_newpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_attacesso_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_attacesso_enviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attacesso_enviarMouseEntered
        btn_attacesso_enviar.setBackground(Color.GREEN);
        btn_attacesso_enviar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_attacesso_enviarMouseEntered

    private void btn_attacesso_enviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attacesso_enviarMouseExited
        btn_attacesso_enviar.setBackground(Color.WHITE);
        btn_attacesso_enviar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_attacesso_enviarMouseExited

    private void btn_attacesso_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attacesso_enviarActionPerformed

        String email = in_attacesso_email.getText();
        if(email.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe um e-mail");
            return;
        } else if (!ValidaEmail.emailValido(email)){
            JOptionPane.showMessageDialog(null, "Por favor, informe um e-mail válido");
            return;
        }
        
        char[] oldpass = in_attacesso_oldpass.getPassword();
        if(oldpass.length == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, informe a senha antiga");
            return;
        }
        
        char[] senhaUser = user.getPassword().toCharArray();
        if(oldpass.length != senhaUser.length){
            JOptionPane.showMessageDialog(null, "A senha antiga está incorreta");
            return;
        }
        
        int count = 0;
        for(int i=0 ; i<oldpass.length ; i++) if(oldpass[i] == senhaUser[i]) count++;
        
        if(count != oldpass.length){
            JOptionPane.showMessageDialog(null, "A senha antiga está incorreta");
            return;
        }
        
        char[] newpass1 = in_attacesso_newpass1.getPassword();
        if(newpass1.length == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, informe a nova senha");
            return;
        } else if (newpass1.length > 20) {
            JOptionPane.showMessageDialog(null, "A senha possui mais de 20 caracteres");
            return;
        }
        
        char[] newpass2 = in_attacesso_newpass2.getPassword();
        if(newpass1.length != newpass2.length){
            JOptionPane.showMessageDialog(null, "As senhas não são iguais ...");
            return;
        }
        
        count = 0;
        for(int i=0 ; i<newpass1.length ; i++) if(newpass1[i] == newpass2[i]) count++;
        if(count != newpass1.length){
            JOptionPane.showMessageDialog(null, "As senhas não são iguais ...");
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja alterar os dados?", 
                "Confirmação de alteração", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.NO_OPTION) return;
        
        user.setEmail(email);
        user.setPassword(new StringBuilder().append(newpass1).toString());
        
        try {
            UsuarioDAO uD = new UsuarioDAO();
            uD.atualizarUsuario(user);
            JOptionPane.showMessageDialog(null, "Dados atualizados com sucesso!");
            if(user.getTipo() == TipoUsuario.USUARIO_CONSUMIDOR)
                new TelaPrincipalUsuario().setUsuario(user);
            else new TelaPrincipalGerente().setUsuario(user);
            dispose();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }

    }//GEN-LAST:event_btn_attacesso_enviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_attacesso_enviar;
    private javax.swing.JTextField in_attacesso_email;
    private javax.swing.JPasswordField in_attacesso_newpass1;
    private javax.swing.JPasswordField in_attacesso_newpass2;
    private javax.swing.JPasswordField in_attacesso_oldpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
