/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.compra;

import br.com.ecommerce.classes.Endereco;
import br.com.ecommerce.classes.Produto;
import br.com.ecommerce.classes.Usuario;
import br.com.ecommerce.classes.ValorTotalCarrinhoInternalFrame;
import br.com.ecommerce.dao.InnerJoinProdutoUsuarioDAO;
import br.com.ecommerce.dao.UsuarioDAO;
import br.com.ecommerce.tables.ModeloVisualizarCarrinho;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class TelaFinalziarCompraConfirmarDados extends ValorTotalCarrinhoInternalFrame {

    /**
     * Creates new form TelaFinalziarCompraConfirmarDados
     */
    
    private Integer id_usuario;
    private Endereco endereco;
    private JDesktopPane desktop;
    private ModeloVisualizarCarrinho modelo;

    public TelaFinalziarCompraConfirmarDados(Integer id_usuario, Endereco endereco, JDesktopPane desktop) {
        initComponents();
        setResizable(false);
        modelo = new ModeloVisualizarCarrinho();
        tabela_finalizar.setModel(modelo);
        this.id_usuario = id_usuario;
        this.endereco = endereco;
        this.desktop = desktop;
        setEndereco();
        setUsuario();
        setLista();
        setTotal(cp_finalizar_total, id_usuario, "Valor total: ");
    }
    
    private void setEndereco(){
        cp_finalizar_rua.setText("Rua: "+endereco.getRua());
        cp_finalizar_cidade.setText("Cidade: "+endereco.getCidade());
        cp_finalizar_complemento.setText("Complemento: "+endereco.getComplemento());
        cp_finalizar_cep.setText("CEP: "+endereco.getCep());
        cp_finalizar_numero.setText("Número/apto: "+endereco.getNumero());
    }
    
    private void setUsuario() {
        List<Usuario> list = null;
        try {   
            list = new UsuarioDAO().listaUsuarios(false, id_usuario);
        } catch(SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(list == null) return;
        Usuario u = list.get(0);
        cp_finalizar_nome.setText("Nome: "+u.getNome());
        cp_finalizar_email.setText("E-mail: "+u.getEmail());
        cp_finalizar_cpf.setText("CPF: "+u.getCpf());
    }
    
    private void setLista(){
        List<Produto> list = null;
        try {
            list = new InnerJoinProdutoUsuarioDAO().listaProdutosUsuario(id_usuario);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(list != null) for(Produto aux: list) modelo.addProduto(aux);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cp_finalizar_nome = new javax.swing.JLabel();
        cp_finalizar_email = new javax.swing.JLabel();
        cp_finalizar_cpf = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_finalizar = new javax.swing.JTable();
        cp_finalizar_total = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cp_finalizar_rua = new javax.swing.JLabel();
        cp_finalizar_cidade = new javax.swing.JLabel();
        cp_finalizar_complemento = new javax.swing.JLabel();
        cp_finalizar_cep = new javax.swing.JLabel();
        cp_finalizar_numero = new javax.swing.JLabel();
        btn_finalizar_voltar = new javax.swing.JButton();
        btn_finalizar_finalizar = new javax.swing.JButton();
        btn_finalizar_continuar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A sua compra está sendo finalizada");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do comprador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        cp_finalizar_nome.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_nome.setText("jLabel2");

        cp_finalizar_email.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_email.setText("jLabel3");

        cp_finalizar_cpf.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_cpf.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cp_finalizar_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(cp_finalizar_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cp_finalizar_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cp_finalizar_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_finalizar_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_finalizar_cpf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        tabela_finalizar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_finalizar);

        cp_finalizar_total.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cp_finalizar_total.setForeground(new java.awt.Color(255, 0, 0));
        cp_finalizar_total.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cp_finalizar_total, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_finalizar_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço de entrega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 14))); // NOI18N

        cp_finalizar_rua.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_rua.setText("jLabel2");

        cp_finalizar_cidade.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_cidade.setText("jLabel3");

        cp_finalizar_complemento.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_complemento.setText("jLabel4");

        cp_finalizar_cep.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_cep.setText("jLabel5");

        cp_finalizar_numero.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        cp_finalizar_numero.setText("jLabel6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(cp_finalizar_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(cp_finalizar_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cp_finalizar_complemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cp_finalizar_cidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cp_finalizar_rua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cp_finalizar_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_finalizar_cidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cp_finalizar_complemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cp_finalizar_cep)
                    .addComponent(cp_finalizar_numero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_finalizar_voltar.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_voltar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_finalizar_voltar.setText("Voltar");
        btn_finalizar_voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_voltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_voltarMouseExited(evt);
            }
        });
        btn_finalizar_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_voltarActionPerformed(evt);
            }
        });

        btn_finalizar_finalizar.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_finalizar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_finalizar_finalizar.setText("Finalizar compra");
        btn_finalizar_finalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_finalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_finalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_finalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_finalizarMouseExited(evt);
            }
        });
        btn_finalizar_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_finalizarActionPerformed(evt);
            }
        });

        btn_finalizar_continuar.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_continuar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_finalizar_continuar.setText("Continuar comprando");
        btn_finalizar_continuar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_continuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_continuarMouseExited(evt);
            }
        });
        btn_finalizar_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_continuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_finalizar_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_finalizar_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_finalizar_finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_finalizar_finalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_finalizar_continuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_finalizar_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finalizar_finalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_finalizarMouseEntered
        btn_finalizar_finalizar.setBackground(new Color(51,153,255));
        btn_finalizar_finalizar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_finalizar_finalizarMouseEntered

    private void btn_finalizar_finalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_finalizarMouseExited
        btn_finalizar_finalizar.setBackground(Color.WHITE);
        btn_finalizar_finalizar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_finalizar_finalizarMouseExited

    private void btn_finalizar_continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_continuarMouseEntered
        btn_finalizar_continuar.setBackground(new Color(51,153,255));
        btn_finalizar_continuar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_finalizar_continuarMouseEntered

    private void btn_finalizar_continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_continuarMouseExited
        btn_finalizar_continuar.setBackground(Color.WHITE);
        btn_finalizar_continuar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_finalizar_continuarMouseExited

    private void btn_finalizar_voltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_voltarMouseEntered
        btn_finalizar_voltar.setBackground(new Color(51,153,255));
        btn_finalizar_voltar.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_finalizar_voltarMouseEntered

    private void btn_finalizar_voltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_voltarMouseExited
        btn_finalizar_voltar.setBackground(Color.WHITE);
        btn_finalizar_voltar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_finalizar_voltarMouseExited

    private void btn_finalizar_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_voltarActionPerformed
        TelaFinalizarCompraEndereco tela = new TelaFinalizarCompraEndereco(id_usuario, desktop);
        desktop.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
        dispose();
    }//GEN-LAST:event_btn_finalizar_voltarActionPerformed

    private void btn_finalizar_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_continuarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_finalizar_continuarActionPerformed

    private void btn_finalizar_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_finalizarActionPerformed
        TelaFinalizarCompra tela = new TelaFinalizarCompra(id_usuario, endereco.getId_endereco());
        desktop.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
        dispose();
    }//GEN-LAST:event_btn_finalizar_finalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_finalizar_continuar;
    private javax.swing.JButton btn_finalizar_finalizar;
    private javax.swing.JButton btn_finalizar_voltar;
    private javax.swing.JLabel cp_finalizar_cep;
    private javax.swing.JLabel cp_finalizar_cidade;
    private javax.swing.JLabel cp_finalizar_complemento;
    private javax.swing.JLabel cp_finalizar_cpf;
    private javax.swing.JLabel cp_finalizar_email;
    private javax.swing.JLabel cp_finalizar_nome;
    private javax.swing.JLabel cp_finalizar_numero;
    private javax.swing.JLabel cp_finalizar_rua;
    private javax.swing.JLabel cp_finalizar_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_finalizar;
    // End of variables declaration//GEN-END:variables
}
