/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.compra;

import br.com.ecommerce.classes.Endereco;
import br.com.ecommerce.classes.PosicaoInternalFrame;
import br.com.ecommerce.dao.EnderecoDAO;
import br.com.ecommerce.tables.ModeloEndereco;
import br.com.ecommerce.view.cadastro.enderecos.TelaCadastroEndereco;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class TelaFinalizarCompraEndereco extends PosicaoInternalFrame {

    /**
     * Creates new form TelaFinalizarCompraEndereco
     */
    
    private Integer id_usuario;
    private JDesktopPane desktop;
    private ModeloEndereco modelo;
    
    public TelaFinalizarCompraEndereco(Integer id, JDesktopPane desktop) {
        initComponents();
        setResizable(false);
        this.id_usuario = id;
        this.desktop = desktop;
        modelo = new ModeloEndereco();
        tabela_finalizar_endereco.setModel(modelo);
        suporteCarregaDados();
    }
    
    private void suporteCarregaDados() {
        List<Endereco> list = null;
        try {
            list = new EnderecoDAO().listaEnderecos(false, id_usuario);
        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(list != null) modelo.setDados(list);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_finalizar_endereco = new javax.swing.JTable();
        btn_finalizar_endereco_proximo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_finalizar_endereco_anterior = new javax.swing.JButton();
        btn_finalizar_endereco_cadastrar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        tabela_finalizar_endereco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_finalizar_endereco);

        btn_finalizar_endereco_proximo.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_endereco_proximo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_finalizar_endereco_proximo.setText("Próximo");
        btn_finalizar_endereco_proximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_endereco_proximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_endereco_proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_endereco_proximoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_endereco_proximoMouseExited(evt);
            }
        });
        btn_finalizar_endereco_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_endereco_proximoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selecione o endereço para entrega");

        btn_finalizar_endereco_anterior.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_endereco_anterior.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_finalizar_endereco_anterior.setText("Anterior");
        btn_finalizar_endereco_anterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_endereco_anterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_endereco_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_endereco_anteriorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_endereco_anteriorMouseExited(evt);
            }
        });
        btn_finalizar_endereco_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_endereco_anteriorActionPerformed(evt);
            }
        });

        btn_finalizar_endereco_cadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_endereco_cadastrar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_finalizar_endereco_cadastrar.setText("Novo endereço");
        btn_finalizar_endereco_cadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_endereco_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_endereco_cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_endereco_cadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_endereco_cadastrarMouseExited(evt);
            }
        });
        btn_finalizar_endereco_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_endereco_cadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_finalizar_endereco_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(btn_finalizar_endereco_anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_finalizar_endereco_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_finalizar_endereco_proximo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btn_finalizar_endereco_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_finalizar_endereco_anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finalizar_endereco_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_proximoActionPerformed
        int index = tabela_finalizar_endereco.getSelectedRow();
        if(index == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um endereço");
            return;
        }
        
        TelaFinalziarCompraConfirmarDados tela = new TelaFinalziarCompraConfirmarDados(id_usuario, modelo.getEnderecoIndex(index), desktop);
        desktop.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
        dispose();
    }//GEN-LAST:event_btn_finalizar_endereco_proximoActionPerformed

    private void btn_finalizar_endereco_proximoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_proximoMouseEntered
        btn_finalizar_endereco_proximo.setForeground(Color.WHITE);
        btn_finalizar_endereco_proximo.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_btn_finalizar_endereco_proximoMouseEntered

    private void btn_finalizar_endereco_proximoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_proximoMouseExited
        btn_finalizar_endereco_proximo.setForeground(Color.BLACK);
        btn_finalizar_endereco_proximo.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_finalizar_endereco_proximoMouseExited

    private void btn_finalizar_endereco_anteriorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_anteriorMouseEntered
        btn_finalizar_endereco_anterior.setBackground(new Color(51,153,255));
        btn_finalizar_endereco_anterior.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_finalizar_endereco_anteriorMouseEntered

    private void btn_finalizar_endereco_anteriorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_anteriorMouseExited
        btn_finalizar_endereco_anterior.setBackground(Color.WHITE);
        btn_finalizar_endereco_anterior.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_finalizar_endereco_anteriorMouseExited

    private void btn_finalizar_endereco_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_anteriorActionPerformed
        TelaFinalizarCompraCarrinho tela = new TelaFinalizarCompraCarrinho(id_usuario, desktop);
        desktop.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
        dispose();
    }//GEN-LAST:event_btn_finalizar_endereco_anteriorActionPerformed

    private void btn_finalizar_endereco_cadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_cadastrarMouseEntered
        btn_finalizar_endereco_cadastrar.setForeground(Color.BLUE);
    }//GEN-LAST:event_btn_finalizar_endereco_cadastrarMouseEntered

    private void btn_finalizar_endereco_cadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_cadastrarMouseExited
        btn_finalizar_endereco_cadastrar.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_finalizar_endereco_cadastrarMouseExited

    private void btn_finalizar_endereco_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_endereco_cadastrarActionPerformed
        TelaCadastroEndereco tela = new TelaCadastroEndereco(id_usuario);
        desktop.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
        dispose();
    }//GEN-LAST:event_btn_finalizar_endereco_cadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_finalizar_endereco_anterior;
    private javax.swing.JButton btn_finalizar_endereco_cadastrar;
    private javax.swing.JButton btn_finalizar_endereco_proximo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_finalizar_endereco;
    // End of variables declaration//GEN-END:variables
}
