/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.compra;

import br.com.ecommerce.classes.Produto;
import br.com.ecommerce.classes.ValorTotalCarrinhoInternalFrame;
import br.com.ecommerce.dao.InnerJoinProdutoUsuarioDAO;
import br.com.ecommerce.enumeracoes.EstadoProduto;
import br.com.ecommerce.tables.ModeloVisualizarCarrinho;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class TelaFinalizarCompraCarrinho extends ValorTotalCarrinhoInternalFrame {

    /**
     * Creates new form TelaFinalizarCompraCarrinho
     */
    
    private Integer id;
    private JDesktopPane desktop;
    private ModeloVisualizarCarrinho modelo;
    
    public TelaFinalizarCompraCarrinho(Integer id, JDesktopPane desktop) {
        initComponents();
        setResizable(false);
        this.id = id;
        this.desktop = desktop;
        modelo = new ModeloVisualizarCarrinho();
        tabela_finalizar_carrinho.setModel(modelo);
        carregaLista();
        setTotal(cp_finalizar_carrinho_total, id, "Valor total: ");
    }
    
    private void carregaLista() {
        List<Produto> list = null;
        try {
            list = new InnerJoinProdutoUsuarioDAO().listaProdutosUsuario(id);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(list != null) 
            for(Produto aux: list) 
                if(aux.getSituacao() == EstadoProduto.INDISPONIVEL)
                    modelo.addProduto(aux);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_finalizar_carrinho_proximo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_finalizar_carrinho = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_finalizar_carrinho_continuar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cp_finalizar_carrinho_total = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        btn_finalizar_carrinho_proximo.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_carrinho_proximo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_finalizar_carrinho_proximo.setText("Próximo");
        btn_finalizar_carrinho_proximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_carrinho_proximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_carrinho_proximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_carrinho_proximoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_carrinho_proximoMouseExited(evt);
            }
        });
        btn_finalizar_carrinho_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_carrinho_proximoActionPerformed(evt);
            }
        });

        tabela_finalizar_carrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_finalizar_carrinho);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Confirme o seu carrinho");

        btn_finalizar_carrinho_continuar.setBackground(new java.awt.Color(255, 255, 255));
        btn_finalizar_carrinho_continuar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_finalizar_carrinho_continuar.setText("Continuar comprando");
        btn_finalizar_carrinho_continuar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_finalizar_carrinho_continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_finalizar_carrinho_continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_finalizar_carrinho_continuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_finalizar_carrinho_continuarMouseExited(evt);
            }
        });
        btn_finalizar_carrinho_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizar_carrinho_continuarActionPerformed(evt);
            }
        });

        cp_finalizar_carrinho_total.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        cp_finalizar_carrinho_total.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(cp_finalizar_carrinho_total, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cp_finalizar_carrinho_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_finalizar_carrinho_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_finalizar_carrinho_proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_finalizar_carrinho_continuar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_finalizar_carrinho_proximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_finalizar_carrinho_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_carrinho_proximoActionPerformed
        TelaFinalizarCompraEndereco tela = new TelaFinalizarCompraEndereco(id, desktop);
        desktop.add(tela);
        tela.setVisible(true);
        tela.setPosicao();
        dispose();
    }//GEN-LAST:event_btn_finalizar_carrinho_proximoActionPerformed

    private void btn_finalizar_carrinho_proximoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_carrinho_proximoMouseEntered
        btn_finalizar_carrinho_proximo.setForeground(Color.WHITE);
        btn_finalizar_carrinho_proximo.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_btn_finalizar_carrinho_proximoMouseEntered

    private void btn_finalizar_carrinho_proximoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_carrinho_proximoMouseExited
        btn_finalizar_carrinho_proximo.setForeground(Color.BLACK);
        btn_finalizar_carrinho_proximo.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_finalizar_carrinho_proximoMouseExited

    private void btn_finalizar_carrinho_continuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_carrinho_continuarMouseEntered
        btn_finalizar_carrinho_continuar.setForeground(Color.WHITE);
        btn_finalizar_carrinho_continuar.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_btn_finalizar_carrinho_continuarMouseEntered

    private void btn_finalizar_carrinho_continuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_finalizar_carrinho_continuarMouseExited
        btn_finalizar_carrinho_continuar.setForeground(Color.BLACK);
        btn_finalizar_carrinho_continuar.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_finalizar_carrinho_continuarMouseExited

    private void btn_finalizar_carrinho_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizar_carrinho_continuarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_finalizar_carrinho_continuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_finalizar_carrinho_continuar;
    private javax.swing.JButton btn_finalizar_carrinho_proximo;
    private javax.swing.JLabel cp_finalizar_carrinho_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_finalizar_carrinho;
    // End of variables declaration//GEN-END:variables
}
