/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.delete.produto;

import br.com.ecommerce.classes.PosicaoInternalFrame;
import br.com.ecommerce.classes.Produto;
import br.com.ecommerce.dao.ProdutoDAO;
import br.com.ecommerce.enumeracoes.EstadoProduto;
import br.com.ecommerce.tables.ModeloMainGerente;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class TelaDeletarProduto extends PosicaoInternalFrame {

    /**
     * Creates new form TelaDeletarProduto
     */
    
    private final boolean TODOS;
    private final Produto PRODUTO;
    private final ModeloMainGerente MODELO;
    
    
    public TelaDeletarProduto(boolean todos, Produto produto, ModeloMainGerente modelo) {
        initComponents();
        setResizable(false);
        this.TODOS = todos;
        this.PRODUTO = produto;
        this.MODELO = modelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_deletarProduto_excluir = new javax.swing.JButton();
        btn_deletarProduto_cancelar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Você tem certeza que deseja excluir este produto?");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apenas produtos em estoque serão excluídos.");

        btn_deletarProduto_excluir.setBackground(new java.awt.Color(255, 0, 0));
        btn_deletarProduto_excluir.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_deletarProduto_excluir.setForeground(new java.awt.Color(255, 255, 255));
        btn_deletarProduto_excluir.setText("Sim, desejo excluir o produto");
        btn_deletarProduto_excluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_deletarProduto_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deletarProduto_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deletarProduto_excluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deletarProduto_excluirMouseExited(evt);
            }
        });
        btn_deletarProduto_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarProduto_excluirActionPerformed(evt);
            }
        });

        btn_deletarProduto_cancelar.setBackground(new java.awt.Color(0, 255, 0));
        btn_deletarProduto_cancelar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btn_deletarProduto_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_deletarProduto_cancelar.setText("Não, desejo manter o produto na loja");
        btn_deletarProduto_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_deletarProduto_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deletarProduto_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_deletarProduto_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_deletarProduto_cancelarMouseExited(evt);
            }
        });
        btn_deletarProduto_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletarProduto_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btn_deletarProduto_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_deletarProduto_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(btn_deletarProduto_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_deletarProduto_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deletarProduto_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deletarProduto_cancelarMouseEntered
        btn_deletarProduto_cancelar.setBackground(new Color(60,179,113));
    }//GEN-LAST:event_btn_deletarProduto_cancelarMouseEntered

    private void btn_deletarProduto_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deletarProduto_cancelarMouseExited
        btn_deletarProduto_cancelar.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn_deletarProduto_cancelarMouseExited

    private void btn_deletarProduto_excluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deletarProduto_excluirMouseEntered
        btn_deletarProduto_excluir.setBackground(new Color(160,82,45));
    }//GEN-LAST:event_btn_deletarProduto_excluirMouseEntered

    private void btn_deletarProduto_excluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_deletarProduto_excluirMouseExited
        btn_deletarProduto_excluir.setBackground(Color.RED);
    }//GEN-LAST:event_btn_deletarProduto_excluirMouseExited

    private void btn_deletarProduto_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarProduto_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_deletarProduto_cancelarActionPerformed

    private void btn_deletarProduto_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletarProduto_excluirActionPerformed
        
        if(!TODOS){
            try {
                new ProdutoDAO().deletarProduto(PRODUTO.getId_produto());
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!");
                dispose();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
            }
        } else {
            List<Produto> list = null;
            try {
                list = new ProdutoDAO().unidadesMesmoProduto(PRODUTO.getNome(), PRODUTO.getDescricao(), 
                        PRODUTO.getCategoria(), PRODUTO.getPreco());
                if(list == null) return;
                for(Produto aux: list) 
                    if(aux.getSituacao() == EstadoProduto.ESTOQUE)
                        new ProdutoDAO().deletarProduto(aux.getId_produto());
                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!");
                dispose();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
            }
        }
        List<Produto> listaTabela = null;
        try {
            listaTabela = new ProdutoDAO().listaProdutosUsuario(true, -1);
        } catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(listaTabela != null) MODELO.setDados(listaTabela);
        
    }//GEN-LAST:event_btn_deletarProduto_excluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_deletarProduto_cancelar;
    private javax.swing.JButton btn_deletarProduto_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
