/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view;

import br.com.ecommerce.view.TelaUnicoOuTodos;
import br.com.ecommerce.classes.PosicaoInternalFrame;
import br.com.ecommerce.classes.Produto;
import br.com.ecommerce.dao.ProdutoDAO;
import br.com.ecommerce.enumeracoes.EstadoProduto;
import br.com.ecommerce.tables.ModeloMainGerente;
import br.com.ecommerce.view.att.produto.TelaAtualizarProduto;
import br.com.ecommerce.view.delete.produto.TelaDeletarProduto;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public class TelaTabelaSelecionar extends PosicaoInternalFrame {

    /**
     * Creates new form TelaTabelaSelecionar
     */
    private final ModeloMainGerente modelo;
    private final ModeloMainGerente MODELO_MAIN;
    private final Integer PROXIMA_TELA;     // 1- tela de atualizar; 2- tela deletar
    
    public TelaTabelaSelecionar(ModeloMainGerente modeloMain, String textoBotao, Integer proximaTela) {
        initComponents();
        setResizable(false);
        this.MODELO_MAIN = modeloMain;
        this.PROXIMA_TELA = proximaTela;
        btn_attproduto_selecionar_selecionar.setText(textoBotao);
        modelo = new ModeloMainGerente();
        tabela_attproduto_selecionar.setModel(modelo);
        suporteCarregaDados();
    }
    
    private void suporteCarregaDados() {
        List<Produto> list = null;
        try {
            list = new ProdutoDAO().listaProdutosUsuario(true, -1);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        if(list == null) return; 
        for(Produto aux: list) modelo.addProduto(aux);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_attproduto_selecionar = new javax.swing.JTable();
        btn_attproduto_selecionar_selecionar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        tabela_attproduto_selecionar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_attproduto_selecionar);

        btn_attproduto_selecionar_selecionar.setBackground(new java.awt.Color(255, 255, 255));
        btn_attproduto_selecionar_selecionar.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        btn_attproduto_selecionar_selecionar.setText("jButton");
        btn_attproduto_selecionar_selecionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_attproduto_selecionar_selecionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attproduto_selecionar_selecionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_attproduto_selecionar_selecionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_attproduto_selecionar_selecionarMouseExited(evt);
            }
        });
        btn_attproduto_selecionar_selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attproduto_selecionar_selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btn_attproduto_selecionar_selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_attproduto_selecionar_selecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_attproduto_selecionar_selecionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attproduto_selecionar_selecionarMouseEntered
        btn_attproduto_selecionar_selecionar.setForeground(Color.WHITE);
        btn_attproduto_selecionar_selecionar.setBackground(Color.GREEN);
    }//GEN-LAST:event_btn_attproduto_selecionar_selecionarMouseEntered

    private void btn_attproduto_selecionar_selecionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attproduto_selecionar_selecionarMouseExited
        btn_attproduto_selecionar_selecionar.setForeground(Color.BLACK);
        btn_attproduto_selecionar_selecionar.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_attproduto_selecionar_selecionarMouseExited

    private void btn_attproduto_selecionar_selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attproduto_selecionar_selecionarActionPerformed
        
        int index = tabela_attproduto_selecionar.getSelectedRow();
        if(index == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um produto na tabela");
            return;
        }
        
        PosicaoInternalFrame tela = null;
        if(PROXIMA_TELA == 1){
            if(modelo.quantidadeProduto(index) == 1)
                tela = new TelaAtualizarProduto(false, index, MODELO_MAIN); 
            else tela = new TelaUnicoOuTodos(index, 1, jDesktopPane1, MODELO_MAIN);

            jDesktopPane1.add(tela);
            tela.setVisible(true);
            tela.setPosicao();
        }
        
        if(PROXIMA_TELA == 2){
            Produto p = modelo.getProdutoIndex(index);
            if(p.getSituacao() == EstadoProduto.INDISPONIVEL || p.getSituacao() == EstadoProduto.VENDIDO){
                JOptionPane.showMessageDialog(null, "Não é possível excluir este produto");
                tabela_attproduto_selecionar.clearSelection();
                return;
            }
            
            if(modelo.quantidadeProduto(index) == 1)
                tela = new TelaDeletarProduto(false, p, MODELO_MAIN);
            else tela = new TelaUnicoOuTodos(index, 2, jDesktopPane1, MODELO_MAIN);    
            
            jDesktopPane1.add(tela);
            tela.setVisible(true);
            tela.setPosicao();
        }

    }//GEN-LAST:event_btn_attproduto_selecionar_selecionarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_attproduto_selecionar_selecionar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_attproduto_selecionar;
    // End of variables declaration//GEN-END:variables
}
