/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ecommerce.view.att.endereco;

import br.com.ecommerce.classes.Endereco;
import br.com.ecommerce.classes.PosicaoInternalFrame;
import br.com.ecommerce.dao.EnderecoDAO;
import br.com.ecommerce.tables.ModeloEndereco;
import br.com.ecommerce.view.login.JTextFieldHint;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class TelaAtualizarEndereco extends PosicaoInternalFrame {

    /**
     * Creates new form TelaAtualizarEndereco
     */
    private Integer id;
    private ModeloEndereco modelo;
    
    public TelaAtualizarEndereco(Integer id_usuario) {
        initComponents();
        btn_attend_enviar.setEnabled(false);
        this.id = id_usuario;
        modelo = new ModeloEndereco();
        tabela_attend.setModel(modelo);
        try {
            List<Endereco> lista = new EnderecoDAO().listaEnderecos(false, id);
            if(lista == null || lista.isEmpty()) return;
            for(Endereco aux: lista)
                modelo.addEnderecoTabela(aux);
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_attend = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        in_attend_rua = new JTextFieldHint(new JTextField(), "", "Nome da rua");
        in_attend_cidade = new JTextFieldHint(new JTextField(), "", "Nome da cidade");
        in_attend_cep = new javax.swing.JFormattedTextField();
        in_attend_complemento = new JTextFieldHint(new JTextField(), "", "Complemento/referências");
        in_attend_numero = new JTextFieldHint(new JTextField(), "", "Número/apartamento");
        btn_attend_alterar = new javax.swing.JButton();
        btn_attend_enviar = new javax.swing.JButton();
        btn_attend_cancelar = new javax.swing.JButton();
        btn_attend_excluir = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(18, 7, 67));

        tabela_attend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela_attend);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rua");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cidade");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CEP");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Número/apartamento");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Complemento");

        in_attend_rua.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attend_rua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_attend_cidade.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attend_cidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_attend_cep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        try {
            in_attend_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        in_attend_cep.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        in_attend_complemento.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attend_complemento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        in_attend_numero.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        in_attend_numero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_attend_alterar.setBackground(new java.awt.Color(204, 204, 204));
        btn_attend_alterar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_attend_alterar.setText("Alterar");
        btn_attend_alterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_attend_alterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attend_alterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_attend_alterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_attend_alterarMouseExited(evt);
            }
        });
        btn_attend_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attend_alterarActionPerformed(evt);
            }
        });

        btn_attend_enviar.setBackground(new java.awt.Color(204, 204, 204));
        btn_attend_enviar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_attend_enviar.setText("Enviar");
        btn_attend_enviar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_attend_enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attend_enviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_attend_enviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_attend_enviarMouseExited(evt);
            }
        });
        btn_attend_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attend_enviarActionPerformed(evt);
            }
        });

        btn_attend_cancelar.setBackground(new java.awt.Color(204, 204, 204));
        btn_attend_cancelar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_attend_cancelar.setText("Cancelar");
        btn_attend_cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_attend_cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attend_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_attend_cancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_attend_cancelarMouseExited(evt);
            }
        });
        btn_attend_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attend_cancelarActionPerformed(evt);
            }
        });

        btn_attend_excluir.setBackground(new java.awt.Color(204, 204, 204));
        btn_attend_excluir.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btn_attend_excluir.setText("Excluir");
        btn_attend_excluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btn_attend_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attend_excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_attend_excluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_attend_excluirMouseExited(evt);
            }
        });
        btn_attend_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attend_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(in_attend_rua)
                            .addComponent(in_attend_cidade)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btn_attend_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btn_attend_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(btn_attend_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btn_attend_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(in_attend_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(in_attend_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(in_attend_complemento))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_attend_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(in_attend_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_attend_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(in_attend_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(in_attend_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_attend_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_attend_alterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btn_attend_enviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_attend_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_attend_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attend_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_attend_cancelarActionPerformed

    private void btn_attend_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attend_excluirActionPerformed
        
        int index = tabela_attend.getSelectedRow();
        if(index == -1){
            JOptionPane.showMessageDialog(null, "Por favor, selecione um endereço para realizar esta operação");
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja excluir?", 
                "Confirmação de exclusão", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.NO_OPTION) return;
        
        
        try {
            EnderecoDAO eD = new EnderecoDAO();
            eD.deletarEndereco(modelo.getEnderecoIndex(index).getId_endereco());
            JOptionPane.showMessageDialog(null, "Endereço excluído com sucesso!");
            modelo.fireTableDataChanged();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
        
    }//GEN-LAST:event_btn_attend_excluirActionPerformed

    private void btn_attend_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attend_enviarActionPerformed
        
        int index = tabela_attend.getSelectedRow();
        
        String rua = in_attend_rua.getText();
        if(rua.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o nome da rua");
            return;
        }
        
        String cidade = in_attend_cidade.getText();
        if(cidade.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o nome da cidade");
            return;
        }
        
        String cep = in_attend_cep.getText();
        if(cep.equals("") || cep.equals("     .   ") || cep == null) {
            JOptionPane.showMessageDialog(null, "Por favor, informe um CEP");
            return;
        }
        
        String numero = in_attend_numero.getText();
        if(numero.equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o número/apartamento do endereço");
            return;
        }
        
        String complemento = in_attend_complemento.getText();
        
        Endereco e = new Endereco(rua, cidade, cep, numero);
        e.setComplemento(complemento);
        e.setId_endereco(modelo.getEnderecoIndex(index).getId_endereco());
        
        try {
            EnderecoDAO eD = new EnderecoDAO();
            eD.atualizarEndereco(e);
            JOptionPane.showMessageDialog(null, "Endereço atualizado com sucesso!");
            dispose();
        } catch(SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro no banco de dados");
        }
    }//GEN-LAST:event_btn_attend_enviarActionPerformed

    private void btn_attend_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attend_alterarActionPerformed
        
        int index = tabela_attend.getSelectedRow();
        if(index == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um endereço para realizar esta operação");
            return;
        }
        
        Endereco teste = modelo.getEnderecoIndex(index);
        btn_attend_enviar.setEnabled(true);
        in_attend_rua.setText(teste.getRua());
        in_attend_cep.setText(teste.getCep());
        in_attend_cidade.setText(teste.getCidade());
        in_attend_numero.setText(teste.getNumero());
        in_attend_complemento.setText(teste.getComplemento() == null? "" : teste.getComplemento());
        
    }//GEN-LAST:event_btn_attend_alterarActionPerformed

    private void btn_attend_alterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_alterarMouseEntered
        btn_attend_alterar.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_attend_alterarMouseEntered

    private void btn_attend_alterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_alterarMouseExited
        btn_attend_alterar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_attend_alterarMouseExited

    private void btn_attend_enviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_enviarMouseEntered
        btn_attend_enviar.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_attend_enviarMouseEntered

    private void btn_attend_enviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_enviarMouseExited
        btn_attend_enviar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_attend_enviarMouseExited

    private void btn_attend_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_cancelarMouseEntered
        btn_attend_cancelar.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_attend_cancelarMouseEntered

    private void btn_attend_cancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_cancelarMouseExited
        btn_attend_cancelar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_attend_cancelarMouseExited

    private void btn_attend_excluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_excluirMouseEntered
        btn_attend_excluir.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_attend_excluirMouseEntered

    private void btn_attend_excluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_attend_excluirMouseExited
        btn_attend_excluir.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_btn_attend_excluirMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_attend_alterar;
    private javax.swing.JButton btn_attend_cancelar;
    private javax.swing.JButton btn_attend_enviar;
    private javax.swing.JButton btn_attend_excluir;
    private javax.swing.JFormattedTextField in_attend_cep;
    private javax.swing.JTextField in_attend_cidade;
    private javax.swing.JTextField in_attend_complemento;
    private javax.swing.JTextField in_attend_numero;
    private javax.swing.JTextField in_attend_rua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_attend;
    // End of variables declaration//GEN-END:variables
}
